setup: #might be a bit hardcoded but idk how else to do it
  home_dir : '$HOME/ultrafaints' #path where I want everything to save
  pckg_dir : 'lsst_ufd' #path to the package

output:
  results_dir : 'results'
  plots_dir : 'plots'


survey : 'dp1' #will change with new data releases
#survey : 'dp2'

dp1:
  repo_config : '/global/cfs/cdirs/lsst/production/gen3/rubin/DP1/repo/butler.yaml'
  collection : 'LSSTComCam/DP1'
  instrument : 'LSSTComCam'
  skymap : 'lsst_cells_v1'
  tract_list : [453, 454, 4849, 5063, 4848, 2394, 2234, 4016, 4017, 4218, 4217, 5525, 5526, 7611, 7610, 7850, 10463, 10464, 10704]
  tract2field_dict : {453: '47 Tuc', 
                      454: '47 Tuc',
                      4849: 'ECDFS', 
                      5063: 'ECDFS',
                      4848: 'ECDFS', 
                      2394: 'EDFS', 
                      2234: 'EDFS',
                      4016: 'Fornax', 
                      4017: 'Fornax', 
                      4218: 'Fornax', 
                      4217: 'Fornax', 
                      5525: 'Rubin_SV_095-25', 
                      5526: 'Rubin_SV_095-25', 
                      7611: 'Seagull', 
                      7610: 'Seagull', 
                      7850: 'Seagull',
                      10463: 'Rubin_SV_38_7', 
                      10464: 'Rubin_SV_38_7', 
                      10704: 'Rubin_SV_38_7'
                      }
  field2tract_dict : {'47 Tuc' : [453], 
                      '47 Tuc' : [454],
                      'ECDFS' : [4849, 5063, 4848], 
                      'EDFS' : [2394, 2234],
                      'Fornax' : [4016, 4017, 4218, 4217], 
                      'Rubin_SV_095-25' : [5525, 5526], 
                      'Seagull' : [7611, 7610, 7850],
                      'Rubin_SV_38_7' : [10463, 10464, 10704]
                      }
  star_gal_sep_fn : 'dp1_fluxratioerr' #can change but for now gonna make a file called this and import the function 

dp2:
 instrument : 'LSSTCam' 
