[project]
name = "alfred"
version = "0.0.0"
        #Major (X.0.0): Changes when you introduce incompatible, breaking updates that disrupt old code
        #Minor (0.X.0): Changes when you add new features while keeping backward compatibility
        #Patch (0.0.X): Changes when you release backward-compatible bug fixes.
authors = [{name = "Kayleigh Excell", email = "kexcell@wisc.edu"}]
requires-python = ">=3.9"
#dependencies

